theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: "/assets/images/logo-text.svg"
    footer: "/assets/images/footer-eu.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
          summary:
            active: true
            source: "meta_description"
            truncate: 0
  persons:
    index:
      layout: list
  posts:
    default_image: false
    date_format: ":date_long"
    index:
      taxonomies: false
  projects:
    index:
      layout: list
  categories:
    index:
      layout: list
      options:
        image: false
  image_sizes:
    sections:
      projects:
        list:
          mobile: 327
      categories:
        large:
          desktop: 864
