theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: "/assets/images/logo-text.svg"
    footer: "/assets/images/footer-eu.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
  projects:
    index:
      layout: list
