theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: "/assets/images/logo-text.svg"
    footer: "/assets/images/footer-eu.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
          summary:
            active: true
            source: "meta_description"
            truncate: 0
  projects:
    index:
      layout: list
  image_sizes:
    sections:
      projects:
        list:
          mobile: 327
